import { createPagesFunctionHandler } from "@react-router/cloudflare";
import { loadWasm } from 'shiki/engine/oniguruma';

// @ts-ignore This is valid but TS doesn't know about .wasm types
await loadWasm(import('shiki/onig.wasm'));

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({ build });
