name = "haydenuwu-blog"
main = "./dist/_worker.js/index.js"

compatibility_date = "2025-07-18"
compatibility_flags = [ "nodejs_compat" ]

[vars]
ATP_IDENTIFIER = "hayden.moe"
ATP_SERVICE = "https://pds.hayden.moe/"

[observability]
enabled = true

[assets]
binding = "ASSETS"
directory = "./dist"

[[kv_namespaces]]
binding = "CACHE"
id = "d7e88adf8eb44f7b9e0544b43bfb27b4"
