name = "haydenuwu-blog"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
bucket = "./build/client"

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "CACHE"
id = "d7e88adf8eb44f7b9e0544b43bfb27b4"

[vars]
ATP_IDENTIFIER = "hayden.moe"
ATP_SERVICE = "https://pds.hayden.moe/"

[observability]
enabled = true
head_sampling_rate = 0.4  # 40% of requests are logged, enough to troubleshoot
