name = "haydenuwu-blog"
compatibility_date = "2023-04-20"
pages_build_output_dir = "./build/client"

[[kv_namespaces]]
binding = "CACHE"
id = "d7e88adf8eb44f7b9e0544b43bfb27b4"

[vars]
ATP_IDENTIFIER = "hayden.moe"
ATP_SERVICE = "https://pds.hayden.moe/"
